### ISSUE TITLE
Thank you for your contribution. May I ask if there is a specific time for open-sourcing?

### ISSUE THREAD

**Issue by red0orange** [ymxlzgy/SG-Bot#1]

**Comment by Bailey-24** [comment]
+1

**Comment by Bailey-24** [comment]
+1

**Comment by ymxlzgy** [comment]
Hi Sorry for the late reply! I will open-source all code in March! Stay tuned! @red0orange @Bailey-24

**Comment by Lotsoliu** [comment]
Hi! sorry to bother you! May I ask when will you release the dataset and code? Thanks for your awesome work!

**Comment by ymxlzgy** [comment]
> Hi! sorry to bother you! May I ask when will you release the dataset and code? Thanks for your awesome work!

Sorry for the delay. I would definitely do it before ICRA begins.

**Comment by ymxlzgy** [comment]
@Lotsoliu , @red0orange , @Bailey-24 Sorry again. I was really busy with other stuff. I have already released the code and data. I am still preparing the rest details. Feel free to leave your issues, and I will solve them as soon as possible!
