### ISSUE TITLE
Can't find the corresponding files  :)

### ISSUE THREAD

**Issue by Lueasecool** [ymxlzgy/SG-Bot#2]
Hello, according to the code in line 163 of the **sgbot_pybullet.py** file `feats_path = os.path.join(goal_scene_path.rsplit('/',1)[0], f'{atlasname}_features_'+goal_scene_path.rsplit('/',1) [1]. replace (f'_view-{view}.json','.pkl'))`, 
I didn't find the corresponding files; could you provide them?  thank you!

您好, 根据sgbot_pybullet.py文件中里163行的代码  `feats_path = os.path.join(goal_scene_path.rsplit('/',1)[0], **f'{atlasname}_features_'+goal_scene_path.rsplit('/',1)[1].replace(f'_view-{view}.json','.pkl'))`，我没有找到对应的文件，您能提供一下这些文件吗？再次感谢**

**Comment by ymxlzgy** [comment]
> Hello, according to the code in line 163 of the **sgbot_pybullet.py** file `feats_path = os.path.join(goal_scene_path.rsplit('/',1)[0], f'{atlasname}_features_'+goal_scene_path.rsplit('/',1) [1]. replace (f'_view-{view}.json','.pkl'))`, I didn't find the corresponding files; could you provide them? thank you!
> 
> 您好, 根据sgbot_pybullet.py文件中里163行的代码 `feats_path = os.path.join(goal_scene_path.rsplit('/',1)[0], **f'{atlasname}_features_'+goal_scene_path.rsplit('/',1)[1].replace(f'_view-{view}.json','.pkl'))`，我没有找到对应的文件，您能提供一下这些文件吗？再次感谢**

Hi,
Sorry for the late reply. I am very busy these days. About your question, have you checked the dataset? Is there any file structured like `/sgbot_dataset/raw/7b4acb843fd4b0b335836c728d324152/atlasnet_add_cup_features_7b4acb843fd4b0b335836c728d324152_0067_6_scene-plate-X-cup_type-in-X-on_goal.pkl`?

**Comment by Lueasecool** [comment]
Thank you for your reply in your busy schedule, regarding the pkl file you said, I really didn't find it in the dataset provided, only the pkl file about raw depth data can be found
感谢您在百忙之中的回复，关于您说的pkl文件，我在提供的数据集中确实没有找到，只有关于raw depth data的pkl文件

**Comment by ymxlzgy** [comment]
Hi, could you check if these things which are absent? https://www.campar.in.tum.de/public_datasets/2023_sgbot_zhai/additional_features.zip

**Comment by Lueasecool** [comment]
Thank you, it's just that these files are missing.
